In [2]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
from scipy.spatial.transform import Rotation

# converts from homogeneous to inhomogeneous coordinates
def Pi(ph):
    return ph[:-1]/ph[-1]
    
# converts from inhomogeneous to homogeneous coordinates
def PiInv(p):
    ones = np.ones((1, p.shape[1]))
    ph = np.vstack((p, ones))
    return ph

def projectpoints(K, R, t, Q):
    Q_homogeneous = PiInv(Q)
    q = np.hstack((R,t)) @ Q_homogeneous
    P = Pi(q)
    p = K @ PiInv(P)
    return p

# Exercise 4
## Mathematical exercises: Direct linear transform (DLT)
In this section consider the 3D points: 
$$
Q_{ijk} = \begin{bmatrix} i \\ j \\ k \end{bmatrix}
$$
where $i \in $ {0, 1}, $j \in $ {0, 1}, and $k \in $ {0, 1}. Consider also a camera with $f$ = 1000 and a resolution of 1920 $\times$ 1080. Furthermore, the camera is transformed such that
$$
R = \begin{bmatrix} \sqrt{1/2} & -\sqrt{1/2} & 0 \\ \sqrt{1/2} & \sqrt{1/2} & 0 \\ 0 & 0 & 1 \end{bmatrix}
$$

### Exercise 4.1
Find the projection matrix $P$ and the projections $q$.

In [4]:
K = np.array([[1000, 0, 960],
              [0, 1000, 540],
              [0, 0, 1]])

R = np.array([[np.sqrt(1/2), -np.sqrt(1/2), 0],
              [np.sqrt(1/2), np.sqrt(1/2), 0],
              [0, 0, 1]])
t = np.array([[0, 0, 10]]).T

Q = np.array([
    [0, 0, 0, 0, 1, 1, 1, 1],
    [0, 0, 1, 1, 0, 0, 1, 1],
    [0, 1, 0, 1, 0, 1, 0, 1],
    np.ones(8)])    
P = K @ np.hstack((R,t))
print("Projection P = :\n", P)
q = P @ Q
q = Pi(q)
print("projects q = : \n", q.round(2))


Projection P = :
 [[ 7.07106781e+02 -7.07106781e+02  9.60000000e+02  9.60000000e+03]
 [ 7.07106781e+02  7.07106781e+02  5.40000000e+02  5.40000000e+03]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  1.00000000e+01]]
projects q = : 
 [[ 960.    960.    889.29  895.72 1030.71 1024.28  960.    960.  ]
 [ 540.    540.    610.71  604.28  610.71  604.28  681.42  668.56]]
